In [7]:
print("Hello World")

Hello World


In [6]:
import numpy as np

list = np.array([1,2,3,4])
print(list)

mat = np.array([[1,3,6,4],
               [1,2,3,4],])
print(mat)

[1 2 3 4]
[[1 3 6 4]
 [1 2 3 4]]
